"""baseline schema

Revision ID: 6bfce6fcdecb
Revises: 
Create Date: 2026-06-15 11:05:24.493489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfce6fcdecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('area_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_unit', sa.String(length=30), nullable=False),
    sa.Column('nama_unit', sa.String(length=100), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=True),
    sa.Column('parent_unit', sa.String(length=100), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_unit', name='uq_area_unit_kode')
    )
    op.create_table('gardu_induk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_gi', sa.String(length=20), nullable=False),
    sa.Column('nama_gi', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_gi')
    )
    op.create_table('monthly_data_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_bulan', name='uq_monthly_data_status_period')
    )
    op.create_table('transfer_antar_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('unit_asal', sa.String(length=100), nullable=False),
    sa.Column('unit_tujuan', sa.String(length=100), nullable=False),
    sa.Column('gi_interkoneksi', sa.String(length=100), nullable=True),
    sa.Column('kode_interbus', sa.String(length=50), nullable=True),
    sa.Column('kwh_transfer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('arah', sa.String(length=10), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kwh_jual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('golongan', sa.String(length=10), nullable=False),
    sa.Column('sub_golongan', sa.String(length=60), nullable=False),
    sa.Column('tegangan', sa.String(length=5), nullable=False),
    sa.Column('kwh', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gi_id', 'periode_bulan', 'sub_golongan', name='uq_kwh_jual_gi_bulan_sub')
    )
    op.create_table('trafo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('kode_trafo', sa.String(length=20), nullable=False),
    sa.Column('nama_trafo', sa.String(length=100), nullable=False),
    sa.Column('kapasitas_mva', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tegangan_kv', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gi_id', 'kode_trafo', name='uq_trafo_gi_kode')
    )
    op.create_table('meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trafo_id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('mu_stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mu_stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mu_faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mu_kwh_wbp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mu_kwh_lwbp1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mu_kwh_lwbp2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mp_stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mp_stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mp_faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mp_kwh_wbp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mp_kwh_lwbp1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mp_kwh_lwbp2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['trafo_id'], ['trafo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trafo_id', 'periode_bulan', name='uq_meter_trafo_bulan')
    )
    op.create_table('penyulang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trafo_id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('kode_penyulang', sa.String(length=30), nullable=False),
    sa.Column('nama_penyulang', sa.String(length=100), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=True),
    sa.Column('area_up3', sa.String(length=100), nullable=True),
    sa.Column('ex_cabang', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['trafo_id'], ['trafo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trafo_id', 'kode_penyulang', name='uq_penyulang_trafo_kode')
    )
    op.create_table('rekap_bulanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('trafo_id', sa.Integer(), nullable=True),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('kwh_mu_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_mp_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_penyulang_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deviasi_mu_mp', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('deviasi_mu_penyulang', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('susut_kwh', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('susut_persen', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('transfer_ekspor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('transfer_impor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['trafo_id'], ['trafo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gi_id', 'trafo_id', 'periode_bulan', name='uq_rekap_gi_trafo_bulan')
    )
    op.create_table('exim_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_rule', sa.String(length=60), nullable=False),
    sa.Column('nama_rule', sa.String(length=150), nullable=True),
    sa.Column('metode', sa.String(length=30), nullable=False),
    sa.Column('penyulang_id', sa.Integer(), nullable=True),
    sa.Column('gi_id', sa.Integer(), nullable=True),
    sa.Column('up3_asal', sa.String(length=100), nullable=True),
    sa.Column('up3_tujuan', sa.String(length=100), nullable=True),
    sa.Column('fungsi', sa.String(length=20), nullable=True),
    sa.Column('arah', sa.String(length=10), nullable=True),
    sa.Column('periode_mulai', sa.Date(), nullable=True),
    sa.Column('periode_selesai', sa.Date(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('source_sheet', sa.String(length=80), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['penyulang_id'], ['penyulang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_rule', name='uq_exim_rule_kode')
    )
    op.create_table('feeder_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penyulang_id', sa.Integer(), nullable=False),
    sa.Column('trafo_id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kwh_wbp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_lwbp1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_lwbp2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wbp_stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wbp_stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wbp_faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lwbp1_stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lwbp1_stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lwbp1_faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lwbp2_stand_awal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lwbp2_stand_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lwbp2_faktor_kali', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual_kwh_wbp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('manual_kwh_lwbp1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('manual_kwh_lwbp2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source_format', sa.String(length=30), nullable=True),
    sa.Column('source_sheet', sa.String(length=80), nullable=True),
    sa.Column('source_row_start', sa.Integer(), nullable=True),
    sa.Column('source_row_end', sa.Integer(), nullable=True),
    sa.Column('flag_alert', sa.Boolean(), nullable=True),
    sa.Column('deviasi_persen', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('anomaly_type', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['penyulang_id'], ['penyulang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trafo_id'], ['trafo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('penyulang_id', 'periode_bulan', name='uq_feeder_penyulang_bulan')
    )
    op.create_table('exim_customer_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('id_pelanggan', sa.String(length=60), nullable=True),
    sa.Column('nama_pelanggan', sa.String(length=150), nullable=True),
    sa.Column('up3_pelanggan', sa.String(length=100), nullable=True),
    sa.Column('kwh_jual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['exim_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exim_kva_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('nama_gardu', sa.String(length=150), nullable=False),
    sa.Column('up3', sa.String(length=100), nullable=False),
    sa.Column('fungsi', sa.String(length=20), nullable=True),
    sa.Column('kva_trafo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porsi_override', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['exim_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exim_monthly_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Date(), nullable=False),
    sa.Column('metode', sa.String(length=30), nullable=False),
    sa.Column('penyulang_id', sa.Integer(), nullable=True),
    sa.Column('gi_id', sa.Integer(), nullable=True),
    sa.Column('up3_asal', sa.String(length=100), nullable=True),
    sa.Column('up3_tujuan', sa.String(length=100), nullable=True),
    sa.Column('fungsi', sa.String(length=20), nullable=True),
    sa.Column('arah', sa.String(length=10), nullable=True),
    sa.Column('kwh_basis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_wbp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_lwbp1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_lwbp2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kwh_transfer', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('porsi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source_sheet', sa.String(length=80), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('versi_hitung', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gi_id'], ['gardu_induk.id'], ),
    sa.ForeignKeyConstraint(['penyulang_id'], ['penyulang.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['exim_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'periode_bulan', 'up3_tujuan', name='uq_exim_result_rule_bulan_tujuan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exim_monthly_result')
    op.drop_table('exim_kva_participant')
    op.drop_table('exim_customer_charge')
    op.drop_table('feeder_reading')
    op.drop_table('exim_rule')
    op.drop_table('rekap_bulanan')
    op.drop_table('penyulang')
    op.drop_table('meter_reading')
    op.drop_table('trafo')
    op.drop_table('kwh_jual')
    op.drop_table('audit_log')
    op.drop_table('transfer_antar_unit')
    op.drop_table('monthly_data_status')
    op.drop_table('gardu_induk')
    op.drop_table('area_unit')
    op.drop_table('app_user')
    # ### end Alembic commands ###
